spring.application.name=Backend

# ===== H2 (banco em memória) =====
spring.datasource.url=jdbc:h2:mem:eventosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA cria/atualiza as tabelas automaticamente a partir das entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== JWT =====
# Chave secreta usada para assinar e validar os tokens (HS256)
app.jwt.secret=VF1o2dETq3HU/5ezmhjETjx5lhYQ4oHS7bbbuMRn4fCV2LBsCLwdqf542di5pLVFZz7FuMLf8U0b5GNSjz+rXg==
# Tempo de expiração do token em milissegundos (24 horas)
app.jwt.expiration=86400000
